newsletter/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'newsletter.views.home', name='home'),
    url(r'^contact/$', 'newsletter.views.contact', name='contact'),
    url(r'^about/$', 'newsletter.views.about', name='about'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^accounts/', include('registration.backends.default.urls')),
]

# if settings.DEBUG:
# 	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

app_name = 'posts'

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

trydjango19/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""trydjango19 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace='posts')),
    url(r'^', include("newsletter.urls", namespace='newsletter')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/models.py
# -*- coding: utf-8 
from django.db import models

# Create your models here.
class SignUp(models.Model):
	email = models.EmailField()
	full_name = models.CharField(max_length=120, blank=True, null=True, verbose_name='Имя')
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self): #Python 3.3 is __str__
		return self.email

newsletter/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import SignUp

class ContactForm(forms.Form):
	full_name = forms.CharField(required=False, label='Ваше имя')
	email = forms.EmailField()
	message = forms.CharField(label='Текст сообщения')


class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name', 'email']
		### exclude = ['full_name']
	
	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_base, provider = email.split("@")
		domain, extension = provider.split('.')
		# if domain == 'mail':
		# 	raise forms.ValidationError("мы не работаем с этим email-провайдером")
		# if not extension == "com":
		# 	raise forms.ValidationError("Please use a valid .com email address")
		return email

	def clean_full_name(self):
		full_name = self.cleaned_data.get('full_name')
		#write validation code.
		return full_name

newsletter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render

from .forms import ContactForm, SignUpForm
from .models import SignUp

def home(request):
	title = 'ОСТАВЬТЕ ЗАЯВКУ'
	form = SignUpForm(request.POST or None)
	context = {
		"title": title,
		"form": form
	}
	if form.is_valid():
		#form.save()
		#print request.POST['email'] #not recommended
		instance = form.save(commit=False)

		full_name = form.cleaned_data.get("full_name")
		if not full_name:
			full_name = "anonymous"
		instance.full_name = full_name
		instance.save()
		context = {
			"title": "Ваша заявка принята!"
		}

	if request.user.is_authenticated() and request.user.is_staff:
		#print(SignUp.objects.all())
		# i = 1
		# for instance in SignUp.objects.all():
		# 	print(i)
		# 	print(instance.full_name)
		# 	i += 1

		queryset = SignUp.objects.all().order_by('-timestamp') #.filter(full_name__iexact="Имя")
		#print(SignUp.objects.all().order_by('-timestamp').filter(full_name__iexact="Точное_имя").count())
		context = {
			"queryset": queryset
		}

	return render(request, "newsletter/home.html", context)



def contact(request):
	title = 'Напишите нам'
	title_align_center = True
	form = ContactForm(request.POST or None)
	if form.is_valid():
		# for key, value in form.cleaned_data.iteritems():
		# 	print key, value
		# 	#print form.cleaned_data.get(key)
		form_email = form.cleaned_data.get("email")
		form_message = form.cleaned_data.get("message")
		form_full_name = form.cleaned_data.get("full_name")
		# print email, message, full_name
		subject = 'Сообщение из формы обратной связи на сайте django18'
		from_email = settings.EMAIL_HOST_USER
		to_email = [from_email, 'rso.just@gmail.com']
		contact_message = "%s: %s via %s"%( 
				form_full_name, 
				form_message, 
				form_email)
		some_html_message = "<h2>%s пишет:</h2><p>%s</p><p>%s</p>"%(form_full_name, form_message, form_email)
		send_mail(subject, 
				contact_message, 
				from_email, 
				to_email, 
				html_message=some_html_message,
				fail_silently=True)

	context = {
		"form": form,
		"title": title,
		"title_align_center": title_align_center,
	}
	return render(request, "newsletter/forms.html", context)

def about(request):
	return render(request, "newsletter/about.html", {})

newsletter/templates/newsletter/about.html
{% extends "newsletter/base.html" %}

{% block content %}

<div class='row'>
	<div class='col-sm-9'>
		<h1>О проекте</h1>
		<p>Это тестовый проект на Django 1.9</p>
		<p>Оставьте заявку на главной странице сайта</p>
		<p>Авторизируйтесь под логином login: 'admin', password: 'django19' чтобы увидеть список заявок.</p>
		<h3>What to do list:</h2>
		<ul>
			<ol>Решить проблему с unicode slug</ol>
			<ol>Почистить\оптимизировать код</ol>
			<ol>Форма обратной связи работает без ошибок кодировки</ol>
			<ol>Регистрацию буду доделывать уже на реальном домене</ol>
			<ol>Доделать всплывающее окно(валидация - чтобы страница не перезагружалась)</ol>
		</ul>
	</div>
</div>

{% endblock %}

newsletter/templates/newsletter/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}Django 1.9{% endblock %}</title>

    {% include 'newsletter/head_css.html' %}

  </head>

  <body>
  {% include 'newsletter/navbar.html' %}

    {% block jumbotron %}
    {% endblock %}

    <div class="container">
      {% block content %}
      {% endblock %}  
    </div>

    {% include "newsletter/javascript.html" %}
  </body>
</html>

newsletter/templates/newsletter/forms.html
{% extends "newsletter/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class='row'>
		<div class='col-sm-6 col-sm-offset-3'>

			{% if title %}
				<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
			{% endif %}

			<form method='POST' action=''>{% csrf_token %}
				{{ form|crispy }}

				<input class='btn btn-default' type='submit' value='Submit' />

			</form>

			<h2>Наши координаты:</h2>
			<p>Москва, ул.Ленина, 45а</p>
			<p>+7 (495) 563 23 87</p>
			<p>support@django.com</p>
		</div>
	</div>
{% endblock %}

newsletter/templates/newsletter/head_css.html
{% load staticfiles %}

<!--     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"> -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<!--     <link href="{% static 'js/bootstrap.min.js' %}" rel="stylesheet"> -->

    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

newsletter/templates/newsletter/home.html
{% extends 'newsletter/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}Welcome | {{ block.super }}{% endblock %}
     
{% block jumbotron %}
	{% if not request.user.is_authenticated %}

		<!-- всплывающее окно-->
		<script type="text/javascript">
			function show(state){
				document.getElementById('window').style.display = state;			
				document.getElementById('wrap').style.display = state; 			
			}
		</script>

		<!-- Задний прозрачный фон-->
		<div onclick="show('none')" id="wrap"></div>

			<!-- Само окно-->
			<div id="window">
						
				<!-- Картинка крестика-->
				<img class="close" onclick="show('none')" src="{% static 'img/close.png' %}">
					
				<p class='lead text-align-center'>{{ title }}</p>

				<form method='POST' action=''>{% csrf_token %}
					{{ form|crispy }}
					<p class='text-align-center'>
						<input class='btn btn-primary' type='submit' value='Откликнуться' />
					</p>
				</form>
			</div>



		<div class="jumbotron">
			<div class="container">
				<div class="row">
					<div class='col-sm-6'>
						<h1>Django 1.9</h1>
						<p>Посадочная страница на базе фреймворка Django 1.9 и Bootstrap. Авторизация реализована при помощи django-registration-redux 1.1. Так же используется библиотека django-crispy-forms 1.4.0</p>

						<p>
							<input class="btn btn-lg btn-primary" style='text-transform: uppercase;' type="button" onclick="show('block')" value="оставить заявку" />
						</p>
					</div>

					<div class='col-sm-4' style='margin-left:50px;'>
						<img src="{% static 'img/pony.png' %}" width='380px' />
			 		</div>
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}




{% block content %}
	{% if request.user.is_authenticated %}
		<h1>Вы авторизовались!</h1>
		{% if queryset %}
			<h2>У вас права редактора</h2>
			<p>И поэтому видите список оставивших заявку.</p>
			<p>Выйдите из своего аккаунта для того, чтобы увидеть главную страницу.</p>
			<table class='table'>
				{% for instance in queryset %}
					<tr><td>{{ forloop.counter }}</td><td>{{ instance.email }}</td><td>{{ instance.full_name }}</td><td>{{ instance.timestamp|timesince }} ago</td></tr>
				{% endfor %}
			</table>

		{% endif %}

	{% else %}

<!-- 	<div class="row">
			<div class="col-sm-3 pull-right">
				<p class='lead text-align-center'>{{ title }}</p>

				<form method='POST' action=''>{% csrf_token %}
					{{ form|crispy }}

					<input class='btn btn-primary' type='submit' value='Откликнуться' />
				</form>
			</div>
		</div>

		<hr /> -->

		      <div class="row">
		        <div class="col-lg-4">
		          <h2>Safari bug warning!</h2>
		          <p class="text-danger">As of v8.0, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
		          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		          <!--<p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>-->
		        </div>
		        <div class="col-lg-4">
		          <h2>Лиды</h2>
		          <p>Авторизируйтесь под логином 'admin', password: 'django19' чтобы увидеть <b>список заявок</b>. Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
		       </div>
		        <div class="col-lg-4">
		          <h2>Heading</h2>
		          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
		        </div>
		      </div>
		      <hr />

		      <footer class="footer">
		        <p>&copy; 2016 Company, Inc.</p>
		      </footer>
	{% endif %}

{% endblock %}

newsletter/templates/newsletter/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

newsletter/templates/newsletter/navbar.html
   {% load staticfiles %}

   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'newsletter:home' %}" title='главная'><img src="{% static 'img/logo.png' %}" alt='logo'/></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'newsletter:home' %}">Главная</a></li>
            <li><a href="{% url 'posts:list' %}">Блог</a></li>
            <li><a href="{% url 'newsletter:about' %}">О проекте</a></li>
            <li><a href="{% url 'newsletter:contact' %}">Контакты</a></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>


          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'newsletter:auth_logout' %}">Выйти</a></li>
            {% else %}
            <li><a href="{% url 'newsletter:registration_register' %}">Регистрация</a></li>
            {% endif %}
          </ul>

          {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
            <form class='navbar-form navbar-right' method='POST' action='{% url "newsletter:auth_login" %}'>{% csrf_token %}
              <div class='form-group'>
                  <input type='text' class='form-control' name='username' placeholder='логин' /> 
              </div>
              <div class='form-group'>
                  <input type='password' class='form-control' name='password' placeholder='пароль' />
              </div>
              <button type='submit' class='btn btn-default'>Войти</button>
          </form>
          {% endif %}


        </div><!--/.nav-collapse -->
      </div>
    </nav>